if (NOT DEFINED OUTPUT)
    message(FATAL_ERROR "OUTPUT is required")
endif ()
if (NOT DEFINED VERTEX_SHADER)
    message(FATAL_ERROR "VERTEX_SHADER is required")
endif ()
if (NOT DEFINED FRAGMENT_SHADER)
    message(FATAL_ERROR "FRAGMENT_SHADER is required")
endif ()

file(READ "${VERTEX_SHADER}" VERTEX_SHADER_SOURCE)
file(READ "${FRAGMENT_SHADER}" FRAGMENT_SHADER_SOURCE)

set(GENERATED_CONTENT "")
string(APPEND GENERATED_CONTENT "#pragma once\n\n")
string(APPEND GENERATED_CONTENT "#include <string_view>\n\n")
string(APPEND GENERATED_CONTENT "namespace shader_resources {\n\n")
string(APPEND GENERATED_CONTENT "inline constexpr std::string_view kTriangleVertex = R\"SHADER(")
string(APPEND GENERATED_CONTENT "${VERTEX_SHADER_SOURCE}")
string(APPEND GENERATED_CONTENT ")SHADER\";\n\n")
string(APPEND GENERATED_CONTENT "inline constexpr std::string_view kTriangleFragment = R\"SHADER(")
string(APPEND GENERATED_CONTENT "${FRAGMENT_SHADER_SOURCE}")
string(APPEND GENERATED_CONTENT ")SHADER\";\n\n")
string(APPEND GENERATED_CONTENT "}  // namespace shader_resources\n")

get_filename_component(OUTPUT_DIRECTORY "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
file(WRITE "${OUTPUT}" "${GENERATED_CONTENT}")
